FROM node:latest

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y nodejs 

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json /usr/src/app

RUN npm install

COPY . /usr/src/app

EXPOSE 7500

CMD ["npm","start"]