version: "3"
services:
    edu-server-app:
        container_name: edu-server-app
        image: edu-server-app
        restart: always
        command: npm run dev
        build: .
        ports:
          - "5000:5000"
        environment:
          MONGOURL: mongodb://mongo:27017/edu-server
          JWTKEY: secret_key_temp
        links:
          - mongo
        volumes:
          - ./:/usr/src/app/
          - /usr/src/app/node_modules
    mongo:
          container_name: mongo
          image: mongo
          volumes:
            - ./data:/data/db
          ports:
            - '27018:27017'
